# Tensors
A tensor is both a container for numbers as well as a set of rules that define transformations between tensors that produce new tensors. In pytorch everything based on tensors. It's multidimensional array. Every tensor has a rank (e.g. scalar has rank=0, vector has rank=1, matrix - 2). 

In [32]:
import torch
torch.random.manual_seed(19)
import numpy as np

## Creating, get the value from scalar

In [16]:
# empty
X = torch.empty(2,2,3)
print('empty with shape', X.shape, '\n', X)

empty with shape torch.Size([2, 2, 3]) 
 tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [19]:
# with random values
X = torch.rand(3, 2, 1)
print('random with shape', X.shape, '\n', X)

random with shape torch.Size([3, 2, 1]) 
 tensor([[[0.7291],
         [0.4305]],

        [[0.2764],
         [0.3478]],

        [[0.5510],
         [0.2707]]])


In [20]:
# with zeros
X = torch.zeros(2, 5)
print('zeros with shape', X.shape, '\n', X)

zeros with shape torch.Size([2, 5]) 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [21]:
# with ones
X = torch.ones(3, 4)
print('ones with shape', X.shape, '\n', X)

ones with shape torch.Size([3, 4]) 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [23]:
# get the simple value
X = torch.tensor([1])
print('X (scalar tensor) =', X)
X = X.item()
print('X (after getting value) =', X)

X (scalar tensor) = tensor([1])
X (after getting value) = 1


## Set the type and device of tensor

In [27]:
# set type
X = torch.tensor([[1],
                  [2]], dtype=torch.float16)
print(X)

# change the type
X = X.to(dtype=torch.int16)
print('After changing the type\n', X)

tensor([[1.],
        [2.]], dtype=torch.float16)
After changing the type
 tensor([[1],
        [2]], dtype=torch.int16)


The heart of every deep learning box is GPU. It's likely going to be the most expensive component in your machine.

Tensors can live on GPU (CUDA) and CPU

In [28]:
# check if GPU is available
torch.cuda.is_available()

False

In [31]:
cpu_tensor = torch.rand(1,2,3)
print(cpu_tensor.device)

# gpu_tensor = cpu_tensor.to("cuda")
# you can use your GPU or GPU provided by Google

cpu


You can make a tensor from numpy array and also converted tensor to numpy array

In [50]:
X = np.array([[1, 2], [15, 22]])
print('X (numpy array):\n', X, '\n')

Y = torch.from_numpy(X)
print('Y (torch tensor):\n', Y, '\n')

Z = Y.numpy()
print('Z (numpy array):\n', Z)

X (numpy array):
 [[ 1  2]
 [15 22]] 

Y (torch tensor):
 tensor([[ 1,  2],
        [15, 22]], dtype=torch.int32) 

Z (numpy array):
 [[ 1  2]
 [15 22]]


## Tensor operations
There are a lot of functions that you can apply to tensors: everything from finding the maximum value to applying a Fourier transform

In [52]:
X = torch.tensor([1, 2])
Y = torch.tensor([2, 4])

In [53]:
# simple
print('X+Y\n', X + Y)
print('X*Y\n', X * Y)
print('Y/X\n', Y / X)

X+Y
 tensor([3, 6])
X*Y
 tensor([2, 8])
Y/X
 tensor([2., 2.])


We can use another method for the same operations

In [55]:
print('X+Y\n', X.add(Y))
print('X*Y\n', X.mul(Y))
print('Y/X\n', Y.div(X))

X+Y
 tensor([3, 6])
X*Y
 tensor([2, 8])
Y/X
 tensor([2., 2.])


If you want to save memory: see if an "in-place" function is defined

In [56]:
# it is always with an appended underscore _
X.add_(Y)
X

tensor([3, 6])

In [59]:
print(f'Maximum of X is {X.max().item()} and index of max is {X.argmax()}')

Maximum of X is 6 and index of max is 1


## Size of tensor
Sometimes we need to resize our tensor. For example: MNIST contains images 28x28, but the way it's packaged is in array of lenght $28*28 = 784$. To use network we should change the size to format  [channels, height, width]

In [63]:
mnist_num = torch.rand(784)
print(f'shape before resize: {mnist_num.shape}')
viewed_num = mnist_num.view(1, 28, 28)
print(f'shape after view() method: {viewed_num.shape}')
reshaped_num = mnist_num.reshape(1, 28, 28)
print(f'shape after reshape() method: {reshaped_num.shape}')

shape before resize: torch.Size([784])
shape after view() method: torch.Size([1, 28, 28])
shape after reshape() method: torch.Size([1, 28, 28])


The difference between `view` and `reshape`: second method return a tensor which could be a view of imput (if it possible because of memory) or could be a copy of input. First method can only return the view so it sometimes throw an error (in this case you should use `.contiguos().view(output_size)` construction)

In [65]:
# torch can determine the size by own
X = torch.rand(3,2, 9)
X = X.reshape(-1, 3)
# this concepth also used when we want to save dimension
print(X.shape)

torch.Size([18, 3])


If we want to rearrange the dimensions of our tensor we can use `permute` function

In [66]:
X = torch.rand(300, 21, 85)
X = X.permute(2, 0, 1)
X.shape

torch.Size([85, 300, 21])